export const PASSWORD_REGEX = /^(?=.*[A-Z])(?=.*[@#$%^&+=]).{8,}$/;

export enum Roles {
  USER = 'USER',
  ARTIST = 'ARTIST',
  'SUPER_ADMIN' = 'SUPER_ADMIN',
}

export enum ERROR_MESSAGES {
  USER_NOT_FOUND = 'User not found',
  MESSAGE_NOT_FOUND = 'Message not found',
  WRONG_PASSWORD = 'Password is incorrect',
  USER_ALREADY_EXISTS = 'User already exists',
  UNABLE_TO_UPDATE_USER = 'Unable to update user',
  CONVERSATION_DONT_EXIST = "Conversation don't exist",
  NOT_AUTHORIZED_ACTION = 'Not authorized for this action',
  INCORRECT_EMAIL_OR_PHONE = 'Incorrect email or phone number',
  UNABLE_TO_PERFORM_ACTION = "User don't have permission to do this action only Artists can do",
  ACCESS_TOKEN_NOT_FOUND = 'Access token is required!',
  ARTIST_UNABLE_TO_PERFORM_ACTION = "Artist don't have permission to do this action",
  USER_CONFIRMATION_EMAIL_FAILED = 'User confirmation email sending failed',
  POST_NOT_FOUND = 'Post not found',
  INVITE_NOT_FOUND = 'Invite not found',
  INVITE_NOT_ACCEPTED = 'Not Allowed to comment on post user has not accepted the post invite',
  COMMENT_NOT_FOUND = 'Comment not found',
  REACTION_NOT_FOUND = 'Reaction not found',
  NOTIFICATION_NOT_FOUND = 'Notification not found',
  USER_NOTIFICATION_TOKEN_NOT_FOUND = 'User notification token not found',
  SIGNATURE_NOT_FOUND = 'Signature not found',
  COMMENT_ALREADY_LIKED_BY_USER = 'Comment is already liked by the User',
  COMMENT_NOT_LIKED_BY_USER = 'Comment is not liked by user',
  COMMENT_OR_REPLY_NOT_BE_SELF_LIKE = 'Not Allowed to Like Own Comment/Reply',
  CANNOT_BLOCK_YOURSELF = 'You cannot block yourself!',
  USER_NOT_BLOCK = 'User is not blocked!',
  USER_DELETED_ERROR = 'User not found or already deleted',
  FORGOT_PASSWORD_FAILED = 'Error in sending forgot password email',
  PASSWORD_RESET_FAILED = 'Password reset failed',
  VERIFICATION_CODE_FAILED = 'Verify Email code sent fail',
  USER_ALREADY_DELETED = 'User is already deleted',
  USER_DELETED = 'User is deleted',
}

export enum SUCCESS_MESSAGES {
  USER_UPDATED_SUCCESS = 'User updated successfully',
  USER_SIGNUP_SUCCESS = 'User signed up successfully',
  USER_SIGN_IN_SUCCESS = 'User sign in successfully',
  USER_CONFIRMATION_EMAIL_SUCCESS = 'User confirmation email sent successfully',
  USER_CONFIRMATION_CODE_SUCCESS = 'User confirmation is successful',
  USER_SIGN_OUT_SUCCESS = 'User Signed Out successful',
  USER_FETCH_SUCCESS = 'User Fetch Out successful',
  USER_LOCATION_UPDATE_SUCCESS = 'User Location is update successfully',
  MESSAGE_SENT_SUCCESS = 'Message sent successfully',
  DISCONNECT_SOCKET_SUCCESS = 'Disconnect from socket successfully',
  CONVERSATION_CREATED_SUCCESS = 'Conversation created successfully',
  CONVERSATION_UPDATED_SUCCESS = 'Conversation updated successfully',
  CONVERSATION_DELETED_SUCCESS = 'Conversation deleted successfully',
  CONVERSATION_FETCHED_SUCCESS = 'Conversations Fetched Successfully',
  MESSAGES_FETCHED_SUCCESS = 'Messages fetched successfully',
  MESSAGE_DELETED_SUCCESS = 'Messages deleted successfully',
  POST_CREATED_SUCCESS = 'Post created successfully',
  GENERIC_POST_SUCCESS = 'Generic Post success',
  POST_UPDATED_SUCCESS = 'Post updated successfully',
  POST_DELETED_SUCCESS = 'Post deleted successfully',
  POST_FETCHED_SUCCESS = 'Post Fetched Successfully',
  POSTS_FETCHED_SUCCESS = 'Posts Fetched Successfully',
  COMMENT_CREATED_SUCCESS = 'Comment added successfully',
  COMMENT_DELETED_SUCCESS = 'Comment deleted successfully',
  REPLAY_CREATED_SUCCESS = 'Reply added successfully',
  LIKE_ADDED_SUCCESS = 'Reaction added successfully',
  LIKE_DELETED_SUCCESS = 'Reaction deleted successfully',
  INVITES_FETCH_SUCCESS = 'Invites Fetch Successfully',
  SIGNED_URL_SUCCESS = 'Signed URL Created Successfully',
  COMMENT_LIKED_SUCCESS = 'Comment liked successfully',
  COMMENT_DISLIKED_SUCCESS = 'Comment disliked successfully',
  POST_COMMENTS_LIKED_SUCCESS = 'Post comments liked successfully',
  REPORT_SAVED_SUCCESS = 'Report saved successfully',
  REPORTS_FETCHED_SUCCESS = 'Report fetched successfully',
  FEEDBACK_SAVED_SUCCESS = 'Feedback saved successfully',
  FEEDBACK_FETCHED_SUCCESS = 'Feedback fetched successfully',
  USER_BLOCK_SUCCESS = 'User Blocked successfully',
  USER_UNBLOCK_SUCCESS = 'User Unblocked successfully',
  USER_DELETE_SUCCESS = 'User delete successfully',
  BLOCK_USER_FETCHED_SUCCESS = 'Blocked users fetched successfully',
  FORGOT_PASSWORD_EMAIL_SENT = 'Password reset confirmation code email sent!',
  PASSWORD_RESET_SUCCESS = 'Password reset successfully',
  VERIFICATION_CODE_SENT = 'Verify email code sent',
}
