export enum MerchDropStatus {
  CREATING = 'CREATING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ProductType {
  TSHIRT = 'TSHIRT',
  HOODIE = 'HOODIE',
  TANK = 'TANK',
  POSTER = 'POSTER',
}

export enum MerchOrderStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  PRODUCTION = 'PRODUCTION',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_APPROVED = 'RETURN_APPROVED',
  RETURN_DENIED = 'RETURN_DENIED',
}

export enum LedgerStatus {
  PENDING = 'PENDING',
  CALCULATED = 'CALCULATED',
  PAID_OUT = 'PAID_OUT',
  REVERSED = 'REVERSED',
}

export enum PayoutBatchStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
